import MainContextProvider from "@/contexts/MainContext";
import "./globals.css";

export const metadata = {
  title: "Chess",
  description: "Generated by Learnstar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainContextProvider>{children}</MainContextProvider>
      </body>
    </html>
  );
}
